
-- require('packer').startup(function(use)
--   use 'wbthomason/packer.nvim'                                                    -- Package manager
--   use 'tpope/vim-fugitive'                                                        -- Git commands in nvim
--   use 'tpope/vim-rhubarb'                                                         -- Fugitive-companion to interact with github
--   use { 'lewis6991/gitsigns.nvim', requires = { 'nvim-lua/plenary.nvim' } }       -- Add git related info in the signs columns and popups
--   use 'numToStr/Comment.nvim'                                                     -- "gc" to comment visual regions/lines
--   use 'nvim-treesitter/nvim-treesitter'                                           -- Highlight, edit, and navigate code
--   use 'nvim-treesitter/nvim-treesitter-textobjects'                               -- Additional textobjects for treesitter
--   use 'nvim-treesitter/nvim-treesitter-refactor'
--   use 'neovim/nvim-lspconfig'                                                     -- Collection of configurations for built-in LSP client
--   use 'williamboman/nvim-lsp-installer'                                           -- Automatically install language servers to stdpath
--   use { 'hrsh7th/nvim-cmp', requires = { 'hrsh7th/cmp-nvim-lsp' } }               -- Autocompletion
--   use { 'L3MON4D3/LuaSnip', requires = { 'saadparwaiz1/cmp_luasnip' } }           -- Snippet Engine and Snippet Expansion
--   use 'mjlbach/onedark.nvim'                                                      -- Theme inspired by Atom
--   use 'nvim-lualine/lualine.nvim'                                                 -- Fancier statusline
--   use 'lukas-reineke/indent-blankline.nvim'                                       -- Add indentation guides even on blank lines
--   use 'tpope/vim-sleuth'                                                          -- Detect tabstop and shiftwidth automatically
--   use { 'nvim-telescope/telescope.nvim', requires = { 'nvim-lua/plenary.nvim' } } -- Fuzzy Finder (files, lsp, etc)
--
--    -- undo history
--   use 'mbbill/undotree'
--
--   use 'voldikss/vimfloaterm'
--   use 'tpope/vim-surround'
--   -- use 'tpope/vim-commentary'
--   -- use 'famiu/bufdelete.nvim'
--   -- Fuzzy Finder Algorithm which requires local dependencies to be built. Only load if `make` is available
--   use { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make', cond = vim.fn.executable "make" == 1 }
-- end)
-- -- stylua: ignore end
--
-- -- When we are bootstrapping a configuration, it doesn't
-- -- make sense to execute the rest of the init.lua.
-- local packer_group = vim.api.nvim_create_augroup('Packer', { clear = true })
-- vim.api.nvim_create_autocmd('BufWritePost', {
--   command = 'source ../init.lua | PackerCompile',
--   group = packer_group,
--   pattern = vim.fn.expand '$MYVIMRC',
-- })
